"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from environs import Env

env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Development Apps
    'core.apps.CoreConfig',
    'apps.users.apps.UsersConfig',
    'apps.books.apps.BooksConfig',

    # Third Party Packages
    'corsheaders',
    'rest_framework',
    'django_filters',
    'djoser',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = ['127.0.0.1'] + [ip[:-1] + '1' for ip in ips]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

print("Connecting to", "sqlite" if env.str("DATABASE_URL", None) is None else "postgres", "db")
DATABASES = {
    "default": dj_database_url.config(
        default=env.str("DATABASE_URL", default="sqlite:///" + str(Path(BASE_DIR) / "db.sqlite3")),
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"

# Media files (User-uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Settings Config
AUTH_USER_MODEL = "users.User"

# REST FRAMEWORK SETTINGS
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'apps.users.api.v1.throttles.StrictUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # global
        'anon': env.str('THROTTLE_ANON_RATE', '100/hour'),
        'user': env.str('THROTTLE_USER_RATE', '1000/day'),

        # auth
        "register": env.str('REGISTER_RATE_THROTTLE', '5/hour'),
        "login": env.str('LOGIN_RATE_THROTTLE', '5/min'),
        "activation": env.str('ACTIVATION_RATE_THROTTLE', '10/min'),
        "resend_activation": env.str('RESEND_ACTIVATION_RATE_THROTTLE', '5/hour'),
        "reset_password": env.str('RESET_PASSWORD_RATE_THROTTLE', '5/hour'),
        "reset_password_confirm": env.str('RESET_PASSWORD_CONFIRM_RATE_THROTTLE', '10/min'),
        "reset_username": env.str('RESET_USERNAME_RATE_THROTTLE', '5/hour'),
        "set_password": env.str('SET_PASSWORD_RATE_THROTTLE', '5/min'),
        "set_username": env.str('SET_USERNAME_RATE_THROTTLE', '5/min'),
    }
}

# DJOSER SETTINGS
DJOSER = {
    "LOGIN_FIELD": env.str("DJOSER_LOGIN_FIELD", "username"),
    "SEND_ACTIVATION_EMAIL": env.bool("DJOSER_SEND_ACTIVATION_EMAIL", True),
    "SEND_CONFIRMATION_EMAIL": env.bool("DJOSER_SEND_CONFIRMATION_EMAIL", True),
    "SEND_USERNAME_RESET_EMAIL": env.bool("DJOSER_SEND_USERNAME_RESET_EMAIL", True),
    "PASSWORD_RESET_CONFIRM_URL": env.str("DJOSER_PASSWORD_RESET_CONFIRM_URL", "reset-password/{uid}/{token}"),
    "USERNAME_RESET_CONFIRM_URL": env.str("DJOSER_USERNAME_RESET_CONFIRM_URL", "reset-username/{uid}/{token}"),
    "ACTIVATION_URL": env.str("DJOSER_ACTIVATION_URL", "activate/{uid}/{token}"),
    "SERIALIZERS": {
        "user_create": "apps.users.api.v1.serializers.user.CustomUserCreateSerializer",
        "user": "apps.users.api.v1.serializers.user.CustomUserSerializer",
        "current_user": "apps.users.api.v1.serializers.user.CustomCurrentUserSerializer",
    },
}

# SIMPLE JWT SETTINGS
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("JWT_ACCESS_TOKEN_MINUTES", 60)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env.int("JWT_REFRESH_TOKEN_DAYS", 1)),
    "ROTATE_REFRESH_TOKENS": env.bool("JWT_ROTATE_REFRESH_TOKENS", True),
    "BLACKLIST_AFTER_ROTATION": env.bool("JWT_BLACKLIST_AFTER_ROTATION", True),
    "AUTH_HEADER_TYPES": env.str("JWT_AUTH_HEADER_TYPE", "Bearer"),
    "SIGNING_KEY": env.str("JWT_SIGNING_KEY", SECRET_KEY),
    "ALGORITHM": env.str("JWT_ALGORITHM", "HS256"),
    "UPDATE_LAST_LOGIN": env.bool("JWT_UPDATE_LAST_LOGIN", True),
}

# Email Settings Config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env.str("EMAIL_HOST", "localhost")
EMAIL_PORT = env.int("EMAIL_PORT", 1025)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", "noreply@example.com")

# CORS settings for frontend access
# Environment variable format: "http://localhost:3000,https://mydomain.com,https://www.mydomain.com"
CORS_ALLOWED_ORIGINS_STRING = env.str("CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STRING.split(",") if origin.strip()]

# Allow all origins during development (you can restrict this in production)
# Set CORS_ALLOW_ALL_ORIGINS=false in production
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)
