# Generated by Django 5.2.6 on 2025-09-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
