# Generated by Django 5.2.6 on 2025-10-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_contentformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('volume', models.PositiveIntegerField(help_text='Book size in MB')),
                ('number_of_page', models.PositiveIntegerField()),
                ('approximate_study_time', models.DurationField(help_text='Study time duration (days, hours, minutes, seconds)')),
                ('publication_date', models.DateField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.category')),
                ('content_formats', models.ManyToManyField(related_name='books', to='books.contentformat')),
                ('languages', models.ManyToManyField(related_name='books', to='books.language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.publisher')),
                ('translators', models.ManyToManyField(blank=True, related_name='books', to='books.translator')),
            ],
        ),
    ]
