# Generated by Django 5.2.11 on 2026-08-28 17:42

import apps.books.utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.books.utils.paths.translator_avatar_upload_path)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
