# Generated by Django 5.2.11 on 2026-08-28 20:09

import apps.books.utils.paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.books.utils.paths.book_avatar_upload_path)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('number_of_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('inventory', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='books.author')),
                ('category', models.ManyToManyField(related_name='books', to='books.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.language')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.publisher')),
                ('translators', models.ManyToManyField(blank=True, related_name='books', to='books.translator')),
            ],
        ),
    ]
